### ISSUE TITLE
address nue build failure: Microsoft.VisualStudio.Services.ExtensionManagement.WebApi

### ISSUE THREAD

**Issue by meganbradley** [docascode/nue#1]
This package cannot currently be built. This is blocking the Team Services .NET doc release.

https://www.nuget.org/packages/Microsoft.VisualStudio.Services.ExtensionManagement.WebApi/

**Comment by Pacort** [comment]
@meganbradley  & @dend Thanks for following up!

**Comment by dend** [comment]
@meganbradley @Pacort 

This is related to this [NuGet issue](https://github.com/NuGet/Home/issues/5333)

**Comment by Pacort** [comment]
@dend and @meganbradley Is there a workaround or a fix coming soon? Thanks!

**Comment by dend** [comment]
Another issue is documented here: https://github.com/NuGet/Home/issues/4512#issuecomment-327037370

This is blocking and we are waiting for a resolution from the NuGet team.

**Comment by dend** [comment]
Closing the issue, as it is external in nature - the Azure Pipelines team needs to ensure that the right dependency constraint is applied (_see NuGet issue for details_).
